### ISSUE TITLE
"TypeError: 'type' object is not subscriptable" when running atlas_generator.py

### ISSUE THREAD

**Issue by ZebulanStanphill** [BalintCsala/TartTin#1]
After following the [manual installation instructions](https://github.com/BalintCsala/TartTin#manual-installation), and running the following command:

```
> python3 atlas_generator.py
```
I get this error:

```
Traceback (most recent call last):
  File "atlas_generator.py", line 347, in <module>
    def get_textures(block: str, data: any, texture_names: list[str]) -> list[str]:
TypeError: 'type' object is not subscriptable
```

I tried going through the automatic method instead, but since it calls `atlas_generator.py` it just runs into the same issue.

Ignoring the error and finishing the process, I end up with a resource pack that appears to do nothing but get rid of the menu screen panorama, so I'm guessing the error that occurs is not one of the expected ones.

I'm using KDE Neon Linux.

**Comment by BalintCsala** [comment]
Can you please post the output of `python3 --version`?

**Comment by ZebulanStanphill** [comment]
>Python 3.8.10

**Comment by BalintCsala** [comment]
Should be fixed with the latest commit, please try downloading it again

**Comment by ZebulanStanphill** [comment]
Thank you for the quick fix!

By the way, I noticed that the pack only works with Fabulous graphics... at least for me, anyway. Might want to add that to the README.
